# title of website
title: website

# description of website
description: hfa111's navigation site

# favicon of website
favicon: "https://github.com/hfa111.png?size=40"

# your website url
url: https://hfa111.github.io/website/

# github profile url
github: "https://github.com/hfa111"

# footer message
footer: © 2021-2021 @hfa111

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 谷歌
          url: http://www.google.com/
        - name: Facebook
          url: http://www.facebook.com/
        - name: Youtube
          url: http://www.youtube.com/
        - name: 推特
          url: http://twitter.com/
        - name: Googlevideo
          url: http://googlevideo.com/
        - name: Instagram
          url: http://www.instagram.com/
        - name: 维基百科
          url: http://www.wikipedia.org/
        - name: youtu.be
          url: http://youtu.be/
        - name: Pinterest
          url: http://www.pinterest.com/
        - name: Github
          url: http://github.com/
        - name: Vimeo
          url: http://vimeo.com/
        - name: Wordpress
          url: http://wordpress.com/
        - name: Bitly
          url: http://bitly.com/
        - name: Blogspot
          url: http://www.blogspot.com/
        - name: Whatsapp
          url: http://www.whatsapp.com/
        - name: Reddit
          url: http://www.reddit.com/
        - name: Deviantart
          url: http://www.deviantart.com/
        - name: Tiktok
          url: http://www.tiktok.com/
        - name: Dropbox
          url: http://www.dropbox.com/
        - name: Tumblr
          url: http://www.tumblr.com/
        - name: Gravatar
          url: http://gravatar.com/
        - name: 纽约时报
          url: http://www.nytimes.com/
        - name: Flickr
          url: http://flickr.com/
        - name: Archive.org
          url: http://archive.org/
        - name: Soundcloud
          url: http://soundcloud.com/
        - name: Medium
          url: http://medium.com/
        - name: 卫报
          url: http://www.theguardian.com/
        - name: bbc.co.uk
          url: http://www.bbc.co.uk/
        - name: 福布斯
          url: http://www.forbes.com/
        - name: BBC
          url: http://www.bbc.com/
        - name: Twitch
          url: http://www.twitch.tv/
        - name: Issuu
          url: http://issuu.com/
        - name: 华盛顿邮报
          url: http://www.washingtonpost.com/
        - name: 每日邮报
          url: http://www.dailymail.co.uk/
        - name: 路透社
          url: http://www.reuters.com/
        - name: Slideshare
          url: http://www.slideshare.net/
        - name: Dailymotion
          url: http://www.dailymotion.com/
        - name: Google.co.uk
          url: http://www.google.co.uk/
        - name: Discord
          url: http://discord.com/
        - name: 彭博社
          url: http://www.bloomberg.com/
