# title of website
title: website

# description of website
description: hfa111's navigation site

# favicon of website
favicon: "https://github.com/hfa111.png?size=40"

# your website url
url: https://hfa111.github.io/website/

# github profile url
github: "https://github.com/hfa111"

# footer message
footer: © 2021-2021 @hfa111

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Google
          url: http://www.google.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Producthunt
          description: 发现新鲜有趣的产品
          url: https://www.producthunt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
